-- ================================================================================
-- Migration : CreateCollaborationSchema
-- Schema    : [Collaboration]
-- Target    : SQL Server 2019+ (T-SQL)
-- Purpose   : Creates all 16 tables that back the NICE Platform Collaboration
--             engine.  Safe to run against an existing database — every CREATE
--             TABLE and every ALTER TABLE is guarded by an IF NOT EXISTS check
--             so the script is fully idempotent.
-- Order     : Tables are created in dependency order so that foreign-key
--             constraints never reference a table that does not yet exist.
-- ================================================================================

PRINT '=== NICE Platform Collaboration — Schema Creation Script ===';
PRINT 'Started: ' + CONVERT(varchar, GETUTCDATE(), 120);
GO

-- ────────────────────────────────────────────────────────────────────────────────
-- 0. Create the [Collaboration] schema if it does not already exist.
--    All platform tables live under this schema to avoid colliding with the
--    host database's existing objects (e.g. [dbo] tables).
-- ────────────────────────────────────────────────────────────────────────────────
IF NOT EXISTS (
    SELECT 1 FROM sys.schemas WHERE name = 'Collaboration'
)
BEGIN
    EXEC('CREATE SCHEMA [Collaboration]');
    PRINT 'Schema [Collaboration] created.';
END
ELSE
    PRINT 'Schema [Collaboration] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 1 : [Collaboration].[Applications]
-- Purpose  : One row per registered client application (tenant).
--            Each application has its own API key, auth provider, blob storage
--            path, and online-capacity limits.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Applications'
)
BEGIN
    CREATE TABLE [Collaboration].[Applications] (

        -- Surrogate primary key (GUID).  Generated by the application layer
        -- via Guid.NewGuid(); no DB default needed.
        [Id]               UNIQUEIDENTIFIER NOT NULL,

        -- Human-readable application name (e.g. "SurveyBot-Prod").
        -- Must be unique across all applications.
        [Name]             NVARCHAR(100)    NOT NULL,

        -- SHA-256 hex of the raw API key issued to this application.
        -- 64 characters exactly.  Never store the raw key.
        [HashedApiKey]     NVARCHAR(64)     NOT NULL,

        -- Authentication provider configured for this application.
        -- Values: 'READI' | 'NICE' | 'ANON'
        [AuthProvider]     NVARCHAR(20)     NOT NULL,

        -- Maximum number of agent seats allowed to be online simultaneously.
        [MaxAgentsOnline]  INT              NOT NULL DEFAULT 0,

        -- Maximum number of external user sessions allowed simultaneously.
        [MaxUsersOnline]   INT              NOT NULL DEFAULT 0,

        -- Root path inside Azure Blob Storage for this application's files
        -- (recordings, attachments).  Example: "tenants/acme-prod".
        [BlobContainerPath] NVARCHAR(200)  NOT NULL DEFAULT '',

        -- Optional HTTPS URL to receive webhook event payloads.
        -- NULL means webhooks are disabled for this application.
        [WebhookUrl]       NVARCHAR(500)    NULL,

        -- Soft-delete flag.  Set to 0 to deactivate without losing history.
        [IsActive]         BIT              NOT NULL DEFAULT 1,

        -- UTC timestamp when the application was first registered.
        [CreatedAt]        DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_Applications] PRIMARY KEY ([Id]),
        CONSTRAINT [UQ_Applications_Name]         UNIQUE ([Name]),
        CONSTRAINT [UQ_Applications_HashedApiKey] UNIQUE ([HashedApiKey])
    );

    PRINT 'Table [Collaboration].[Applications] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Applications] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 2 : [Collaboration].[ApplicationUserTypeConfigs]
-- Purpose  : Per-application, per-user-type feature flags.
--            One row for each UserType ('External', 'Internal', 'Agent',
--            'Supervisor', 'StandAlone') per application.
--            These rows replace the old hard-coded JSON application config.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'ApplicationUserTypeConfigs'
)
BEGIN
    CREATE TABLE [Collaboration].[ApplicationUserTypeConfigs] (

        -- Surrogate PK.
        [Id]                      UNIQUEIDENTIFIER NOT NULL,

        -- The application this config row belongs to.
        [ApplicationId]           UNIQUEIDENTIFIER NOT NULL,

        -- The user type this row configures.
        -- Values: 'External' | 'Internal' | 'Agent' | 'Supervisor' | 'StandAlone'
        [UserType]                NVARCHAR(30)     NOT NULL,

        -- ── External / Internal user options ──────────────────────────────────

        -- Chat routing mode for end-users.
        -- Values: 'OnlyBot' | 'OnlyHuman' | 'BotThenHuman' | 'TalkWithAvailableAgent'
        -- NULL for user types that do not participate in chat (e.g. StandAlone).
        [ChatMode]                NVARCHAR(50)     NULL,

        -- Whether users of this type may initiate a screen-share in a session.
        [CanShareScreen]          BIT              NOT NULL DEFAULT 0,

        -- Whether a screen recording must be created automatically when this
        -- user type starts a screen share.
        [NeedScreenRecording]     BIT              NOT NULL DEFAULT 0,

        -- ── Agent / Supervisor options ─────────────────────────────────────────

        -- Whether agents of this type are permitted to transfer/hand-off a
        -- collaboration to a different agent.
        [CanHandOffToOtherAgent]  BIT              NOT NULL DEFAULT 0,

        -- Maximum number of concurrent collaborations this user type may handle.
        -- 0 = unlimited.
        [MaxParallelChats]        INT              NOT NULL DEFAULT 1,

        -- ── StandAlone options ────────────────────────────────────────────────

        -- Whether screen recording starts automatically the moment a StandAlone
        -- session connects (no manual "Start Recording" required).
        [AutoRecordScreen]        BIT              NOT NULL DEFAULT 0,

        -- Whether supervisors are permitted to watch a StandAlone session live
        -- via the StandaloneMonitor page.
        [SupervisorCanWatchLive]  BIT              NOT NULL DEFAULT 0,

        CONSTRAINT [PK_ApplicationUserTypeConfigs] PRIMARY KEY ([Id]),

        -- Enforce uniqueness: only one config row per UserType per application.
        CONSTRAINT [UQ_AppUserTypeConfigs_AppType]
            UNIQUE ([ApplicationId], [UserType]),

        CONSTRAINT [FK_AppUserTypeConfigs_Applications]
            FOREIGN KEY ([ApplicationId])
            REFERENCES [Collaboration].[Applications] ([Id])
            ON DELETE CASCADE
    );

    PRINT 'Table [Collaboration].[ApplicationUserTypeConfigs] created.';
END
ELSE
    PRINT 'Table [Collaboration].[ApplicationUserTypeConfigs] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 3 : [Collaboration].[Users]
-- Purpose  : Master record for every person who has ever authenticated with the
--            platform.  External-user IDs come from the auth provider (READI /
--            NICE); anonymous users receive a generated ID.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Users'
)
BEGIN
    CREATE TABLE [Collaboration].[Users] (

        -- Surrogate PK.
        [Id]             UNIQUEIDENTIFIER NOT NULL,

        -- The user ID as issued by the upstream auth provider.
        -- For READI/NICE users this is the provider's own GUID or employee ID.
        -- Must be unique across all users.
        [ExternalUserId] NVARCHAR(256)    NOT NULL,

        -- User's given name as provided at login / onboarding.
        [FirstName]      NVARCHAR(100)    NOT NULL DEFAULT '',

        -- User's family name.
        [LastName]       NVARCHAR(100)    NOT NULL DEFAULT '',

        -- Email address.  Required for agents and supervisors; may be NULL for
        -- anonymous external users.
        [Email]          NVARCHAR(256)    NULL,

        -- Soft-delete flag.
        [IsActive]       BIT              NOT NULL DEFAULT 1,

        -- UTC timestamp of first onboarding.
        [CreatedAt]      DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_Users] PRIMARY KEY ([Id]),
        CONSTRAINT [UQ_Users_ExternalUserId] UNIQUE ([ExternalUserId])
    );

    -- Speed up lookup by email (used during login / onboarding).
    CREATE INDEX [IX_Users_Email] ON [Collaboration].[Users] ([Email]);

    PRINT 'Table [Collaboration].[Users] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Users] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 4 : [Collaboration].[ApplicationUsers]
-- Purpose  : Junction table linking users to applications with a role.
--            A person can have different roles in different applications
--            (e.g. Agent in App-A, Supervisor in App-B).
--            Composite PK of (ApplicationId, UserId).
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'ApplicationUsers'
)
BEGIN
    CREATE TABLE [Collaboration].[ApplicationUsers] (

        -- FK to the application.
        [ApplicationId] UNIQUEIDENTIFIER NOT NULL,

        -- FK to the user.
        [UserId]        UNIQUEIDENTIFIER NOT NULL,

        -- Role within this application.
        -- Values: 'User' | 'Agent' | 'Supervisor' | 'Admin' | 'Bot'
        [Role]          NVARCHAR(30)     NOT NULL,

        -- Soft-delete flag.  Set to 0 to revoke access without losing history.
        [IsActive]      BIT              NOT NULL DEFAULT 1,

        -- UTC timestamp when the user was added to this application.
        [AddedAt]       DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_ApplicationUsers]
            PRIMARY KEY ([ApplicationId], [UserId]),

        CONSTRAINT [FK_ApplicationUsers_Applications]
            FOREIGN KEY ([ApplicationId])
            REFERENCES [Collaboration].[Applications] ([Id])
            ON DELETE CASCADE,

        CONSTRAINT [FK_ApplicationUsers_Users]
            FOREIGN KEY ([UserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE CASCADE
    );

    PRINT 'Table [Collaboration].[ApplicationUsers] created.';
END
ELSE
    PRINT 'Table [Collaboration].[ApplicationUsers] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 5 : [Collaboration].[CurrentSessions]
-- Purpose  : Live presence table.  One row per active user session.
--            Rows are DELETED when a session disconnects; historical data is
--            written to UserSessions (Table 6) at connect time.
--            Used for real-time presence queries: "who is online right now?",
--            "which agent is in which collaboration?".
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'CurrentSessions'
)
BEGIN
    CREATE TABLE [Collaboration].[CurrentSessions] (

        -- Session PK.  This is the same GUID that is embedded in the JWT
        -- as the 'sid' (session-id) claim, so token validation is a simple
        -- EXISTS check against this table.
        [Id]                    UNIQUEIDENTIFIER NOT NULL,

        -- The application this session belongs to.
        [ApplicationId]         UNIQUEIDENTIFIER NOT NULL,

        -- The authenticated user.
        [UserId]                UNIQUEIDENTIFIER NOT NULL,

        -- Role the user connected with.
        -- Values: 'External' | 'Internal' | 'Agent' | 'Supervisor' | 'StandAlone'
        [UserType]              NVARCHAR(30)     NOT NULL,

        -- Auth provider used to validate the initial token.
        -- Values: 'READI' | 'NICE' | 'ANON'
        [AuthProvider]          NVARCHAR(20)     NOT NULL,

        -- The SignalR connection ID for the active WebSocket connection.
        -- Updated on reconnect.  NULL until the hub OnConnectedAsync fires.
        [SignalRConnectionId]   NVARCHAR(256)    NULL,

        -- UTC time the session was established (token validated and row inserted).
        [ConnectedAt]           DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time of the most recent heartbeat ping from the client.
        -- Used by background jobs to detect stale/orphaned sessions.
        [LastSeenAt]            DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- The collaboration this user is currently inside, if any.
        -- NULL when the user is online but not in a collaboration.
        -- NOT a FK to Collaborations — avoids cascading-delete complications
        -- when a collaboration ends while the session is still open.
        [CurrentCollaborationId] UNIQUEIDENTIFIER NULL,

        CONSTRAINT [PK_CurrentSessions] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_CurrentSessions_Applications]
            FOREIGN KEY ([ApplicationId])
            REFERENCES [Collaboration].[Applications] ([Id])
            ON DELETE CASCADE,

        CONSTRAINT [FK_CurrentSessions_Users]
            FOREIGN KEY ([UserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE CASCADE
    );

    -- Fast lookup: "find all sessions for an application".
    CREATE INDEX [IX_CurrentSessions_ApplicationId]
        ON [Collaboration].[CurrentSessions] ([ApplicationId]);

    -- Fast presence query: "who of type X is online in application Y?"
    CREATE INDEX [IX_CurrentSessions_AppId_UserType]
        ON [Collaboration].[CurrentSessions] ([ApplicationId], [UserType]);

    PRINT 'Table [Collaboration].[CurrentSessions] created.';
END
ELSE
    PRINT 'Table [Collaboration].[CurrentSessions] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 6 : [Collaboration].[UserSessions]
-- Purpose  : Permanent historical record of every session opened by every user.
--            A row is written at connect time; EndedAt and DurationSeconds are
--            filled when the session closes.  Never deleted.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'UserSessions'
)
BEGIN
    CREATE TABLE [Collaboration].[UserSessions] (

        -- Surrogate PK.
        [Id]              UNIQUEIDENTIFIER NOT NULL,

        -- The application the session belonged to.
        [ApplicationId]   UNIQUEIDENTIFIER NOT NULL,

        -- The user who opened the session.
        [UserId]          UNIQUEIDENTIFIER NOT NULL,

        -- Role the user was connected as.
        -- Values: 'External' | 'Internal' | 'Agent' | 'Supervisor' | 'StandAlone'
        [UserType]        NVARCHAR(30)     NOT NULL,

        -- Auth provider used for the session.
        [AuthProvider]    NVARCHAR(20)     NOT NULL,

        -- UTC time the session started.
        [ConnectedAt]     DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the session ended.  NULL while the session is still open
        -- (cross-reference with CurrentSessions to check live status).
        [EndedAt]         DATETIME2        NULL,

        -- Session length in whole seconds.  Computed and stored when the session
        -- closes: DATEDIFF(second, ConnectedAt, EndedAt).
        [DurationSeconds] INT              NULL,

        -- Why the session ended.
        -- Values: 'Disconnected' | 'Timeout' | 'Kicked' | 'ServerRestart'
        [EndReason]       NVARCHAR(50)     NULL,

        CONSTRAINT [PK_UserSessions] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_UserSessions_Applications]
            FOREIGN KEY ([ApplicationId])
            REFERENCES [Collaboration].[Applications] ([Id])
            ON DELETE CASCADE,

        CONSTRAINT [FK_UserSessions_Users]
            FOREIGN KEY ([UserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE CASCADE
    );

    CREATE INDEX [IX_UserSessions_UserId]
        ON [Collaboration].[UserSessions] ([UserId]);

    CREATE INDEX [IX_UserSessions_ApplicationId]
        ON [Collaboration].[UserSessions] ([ApplicationId]);

    -- Reporting queries often filter by date range.
    CREATE INDEX [IX_UserSessions_ConnectedAt]
        ON [Collaboration].[UserSessions] ([ConnectedAt]);

    PRINT 'Table [Collaboration].[UserSessions] created.';
END
ELSE
    PRINT 'Table [Collaboration].[UserSessions] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 7 : [Collaboration].[SessionCache]
-- Purpose  : Lightweight SQL-backed key-value store.  Replaces Redis for
--            ephemeral session data: in-progress collaboration mappings,
--            agent queue entries, pending transfer tokens, etc.
--            A background job periodically deletes rows where ExpiresAt < GETUTCDATE().
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'SessionCache'
)
BEGIN
    CREATE TABLE [Collaboration].[SessionCache] (

        -- Surrogate PK.  Uses NEWSEQUENTIALID() so inserts are clustered
        -- in order and avoid page splits.
        [Id]         UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),

        -- Application-defined cache key.  Unique; max 500 chars.
        -- Naming convention: "{category}:{discriminator}"
        --   e.g. "session:abc123", "queue:appId", "collab:userId"
        [CacheKey]   NVARCHAR(500)    NOT NULL,

        -- JSON-serialised value, or a plain scalar string for simple values.
        -- No length cap — stored as nvarchar(max).
        [CacheValue] NVARCHAR(MAX)    NOT NULL,

        -- UTC expiry.  NULL = never expires automatically.
        -- The cleanup job selects WHERE ExpiresAt < GETUTCDATE().
        [ExpiresAt]  DATETIME2        NULL,

        -- UTC timestamp when the row was first inserted or last upserted.
        [CreatedAt]  DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_SessionCache] PRIMARY KEY ([Id]),
        CONSTRAINT [UQ_SessionCache_CacheKey] UNIQUE ([CacheKey])
    );

    -- Expiry sweeps: fast filter for rows that have expired.
    CREATE INDEX [IX_SessionCache_ExpiresAt]
        ON [Collaboration].[SessionCache] ([ExpiresAt]);

    PRINT 'Table [Collaboration].[SessionCache] created.';
END
ELSE
    PRINT 'Table [Collaboration].[SessionCache] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 8 : [Collaboration].[Collaborations]
-- Purpose  : The core collaboration session record.  One row per interaction.
--            Chat-based flows create the row on the first message; StandAlone
--            flows create it immediately on session start.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Collaborations'
)
BEGIN
    CREATE TABLE [Collaboration].[Collaborations] (

        -- Surrogate PK.
        [Id]             UNIQUEIDENTIFIER NOT NULL,

        -- The application that owns this collaboration.
        [ApplicationId]  UNIQUEIDENTIFIER NOT NULL,

        -- The primary external user being served.  Nullable because StandAlone
        -- sessions may not be linked to an external user record.
        [ExternalUserId] UNIQUEIDENTIFIER NULL,

        -- Lifecycle state.
        -- Values: 'Pending' | 'BotHandling' | 'AgentHandling' | 'Ended'
        --         | 'Transferred' | 'Abandoned'
        [Status]         NVARCHAR(30)     NOT NULL DEFAULT 'Pending',

        -- Chat mode snapshot captured at collaboration creation time (from the
        -- ApplicationUserTypeConfig in effect at that moment).
        -- Values: 'OnlyBot' | 'OnlyHuman' | 'BotThenHuman' | 'TalkWithAvailableAgent'
        [ChatMode]       NVARCHAR(50)     NOT NULL DEFAULT '',

        -- Whether screen sharing is currently active in this collaboration.
        [IsScreenSharing] BIT             NOT NULL DEFAULT 0,

        -- Whether a recording has been started (or completed) for this collaboration.
        [IsRecorded]      BIT             NOT NULL DEFAULT 0,

        -- UTC time the collaboration was created.
        [CreatedAt]      DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the collaboration ended.  NULL while still active.
        [EndedAt]        DATETIME2        NULL,

        -- How the collaboration concluded.
        -- Values: 'Completed' | 'Abandoned' | 'Transferred' | 'TimedOut'
        [EndReason]      NVARCHAR(50)     NULL,

        CONSTRAINT [PK_Collaborations] PRIMARY KEY ([Id]),

        -- RESTRICT delete so we never silently orphan a collaboration by deleting
        -- its application.  Deactivate the application instead (IsActive = 0).
        CONSTRAINT [FK_Collaborations_Applications]
            FOREIGN KEY ([ApplicationId])
            REFERENCES [Collaboration].[Applications] ([Id])
            ON DELETE NO ACTION,

        -- If the external user is deleted, NULL the FK rather than cascade-delete
        -- the collaboration history.
        CONSTRAINT [FK_Collaborations_Users]
            FOREIGN KEY ([ExternalUserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE SET NULL
    );

    CREATE INDEX [IX_Collaborations_ApplicationId]
        ON [Collaboration].[Collaborations] ([ApplicationId]);

    -- Dashboard query: "show all active collaborations".
    CREATE INDEX [IX_Collaborations_Status]
        ON [Collaboration].[Collaborations] ([Status]);

    -- Reporting: date-range filters.
    CREATE INDEX [IX_Collaborations_CreatedAt]
        ON [Collaboration].[Collaborations] ([CreatedAt]);

    PRINT 'Table [Collaboration].[Collaborations] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Collaborations] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 9 : [Collaboration].[Participants]
-- Purpose  : Tracks every user who joined a collaboration with timestamps.
--            Multiple rows per collaboration (one per join event per user).
--            Agents re-joining after a transfer each get a new row.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Participants'
)
BEGIN
    CREATE TABLE [Collaboration].[Participants] (

        -- Surrogate PK.
        [Id]              UNIQUEIDENTIFIER NOT NULL,

        -- The collaboration this participant belongs to.
        [CollaborationId] UNIQUEIDENTIFIER NOT NULL,

        -- The user who participated.
        [UserId]          UNIQUEIDENTIFIER NOT NULL,

        -- Role at the time of joining.
        -- Values: 'External' | 'Internal' | 'Agent' | 'Supervisor' | 'StandAlone'
        [UserType]        NVARCHAR(30)     NOT NULL,

        -- UTC time the user entered the collaboration.
        [JoinedAt]        DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the user left the collaboration.  NULL if still present.
        [LeftAt]          DATETIME2        NULL,

        -- Whether this participant is currently the primary agent responsible
        -- for handling the collaboration.  Only one participant should have this
        -- set to 1 at any given time.
        [IsActiveAgent]   BIT              NOT NULL DEFAULT 0,

        CONSTRAINT [PK_Participants] PRIMARY KEY ([Id]),

        -- Cascade: deleting a collaboration removes its participant rows.
        CONSTRAINT [FK_Participants_Collaborations]
            FOREIGN KEY ([CollaborationId])
            REFERENCES [Collaboration].[Collaborations] ([Id])
            ON DELETE CASCADE,

        -- RESTRICT: never silently discard participant history by deleting a user.
        CONSTRAINT [FK_Participants_Users]
            FOREIGN KEY ([UserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE NO ACTION
    );

    CREATE INDEX [IX_Participants_CollaborationId]
        ON [Collaboration].[Participants] ([CollaborationId]);

    -- Find all collaborations a specific user has been in.
    CREATE INDEX [IX_Participants_CollabId_UserId]
        ON [Collaboration].[Participants] ([CollaborationId], [UserId]);

    PRINT 'Table [Collaboration].[Participants] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Participants] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 10 : [Collaboration].[Messages]
-- Purpose  : Chat messages sent by human participants.
--            Bot-generated messages are stored separately in BotMessages (Table 12)
--            to keep analytics and re-training pipelines clean.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Messages'
)
BEGIN
    CREATE TABLE [Collaboration].[Messages] (

        -- Surrogate PK.
        [Id]              UNIQUEIDENTIFIER NOT NULL,

        -- The collaboration this message belongs to.
        [CollaborationId] UNIQUEIDENTIFIER NOT NULL,

        -- The user who sent the message.
        [SenderId]        UNIQUEIDENTIFIER NOT NULL,

        -- Role of the sender at send time.
        -- Values: 'External' | 'Internal' | 'Agent' | 'Supervisor'
        [SenderType]      NVARCHAR(30)     NOT NULL,

        -- The text body of the message.  NULL for attachment-only messages.
        [Body]            NVARCHAR(4000)   NULL,

        -- Message classification.
        -- 'Text'       — normal visible message.
        -- 'Attachment' — message body may be null; see Attachments table.
        -- 'System'     — platform-generated notice (e.g. "Agent joined").
        -- 'Whisper'    — internal note visible only to agents / supervisors.
        [MessageType]     NVARCHAR(20)     NOT NULL DEFAULT 'Text',

        -- Whether this message has been soft-deleted.  When true the Body is
        -- replaced with a placeholder; attachments are not removed.
        [IsDeleted]       BIT              NOT NULL DEFAULT 0,

        -- UTC time the message was sent.
        [SentAt]          DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the external user first read the message.  NULL until read.
        -- Used to drive "delivered/read" receipt indicators in the UI.
        [ReadAt]          DATETIME2        NULL,

        CONSTRAINT [PK_Messages] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_Messages_Collaborations]
            FOREIGN KEY ([CollaborationId])
            REFERENCES [Collaboration].[Collaborations] ([Id])
            ON DELETE CASCADE,

        -- RESTRICT: preserve message history even if the sender's user row
        -- is ever deactivated / pseudonymised.
        CONSTRAINT [FK_Messages_Sender]
            FOREIGN KEY ([SenderId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE NO ACTION
    );

    -- Primary message-list query: "give me all messages for collaboration X in order".
    CREATE INDEX [IX_Messages_CollaborationId]
        ON [Collaboration].[Messages] ([CollaborationId]);

    -- Timeline / pagination queries.
    CREATE INDEX [IX_Messages_SentAt]
        ON [Collaboration].[Messages] ([SentAt]);

    PRINT 'Table [Collaboration].[Messages] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Messages] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 11 : [Collaboration].[Attachments]
-- Purpose  : File / media attachments linked to a Message.
--            The file itself lives in Azure Blob Storage; this row holds the
--            metadata needed to generate a SAS URL and display a preview.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Attachments'
)
BEGIN
    CREATE TABLE [Collaboration].[Attachments] (

        -- Surrogate PK.
        [Id]             UNIQUEIDENTIFIER NOT NULL,

        -- The message this attachment belongs to.
        [MessageId]      UNIQUEIDENTIFIER NOT NULL,

        -- Original filename as uploaded by the sender (e.g. "screenshot.png").
        -- Max 260 chars (Windows MAX_PATH).
        [FileName]       NVARCHAR(260)    NOT NULL,

        -- MIME type of the file (e.g. "image/png", "application/pdf").
        [ContentType]    NVARCHAR(100)    NOT NULL,

        -- Size of the uploaded file in bytes.
        [FileSizeBytes]  BIGINT           NOT NULL DEFAULT 0,

        -- Full Blob Storage URI (or relative container path) pointing to the file.
        -- Max 1000 chars to accommodate long signed URLs.
        [BlobUri]        NVARCHAR(1000)   NOT NULL,

        -- Thumbnail Blob URI for images and videos.
        -- NULL for other file types (PDFs, documents, etc.).
        [ThumbnailUri]   NVARCHAR(1000)   NULL,

        -- UTC time the file upload completed.
        [UploadedAt]     DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_Attachments] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_Attachments_Messages]
            FOREIGN KEY ([MessageId])
            REFERENCES [Collaboration].[Messages] ([Id])
            ON DELETE CASCADE
    );

    PRINT 'Table [Collaboration].[Attachments] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Attachments] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 12 : [Collaboration].[BotMessages]
-- Purpose  : Messages generated by the Azure AI Foundry bot.
--            Kept separate from human Messages to support bot analytics,
--            confidence-score tracking, and model re-training pipelines.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'BotMessages'
)
BEGIN
    CREATE TABLE [Collaboration].[BotMessages] (

        -- Surrogate PK.
        [Id]               UNIQUEIDENTIFIER NOT NULL,

        -- The collaboration this bot turn belongs to.
        [CollaborationId]  UNIQUEIDENTIFIER NOT NULL,

        -- The user input or system prompt that triggered this bot response.
        -- May be NULL for proactive bot messages.
        [Prompt]           NVARCHAR(2000)   NULL,

        -- The bot's generated reply text.
        [Response]         NVARCHAR(4000)   NOT NULL,

        -- Intent detected by the bot model, if applicable.
        -- Examples: 'CheckOrderStatus', 'RequestRefund', 'GeneralQuery'.
        -- NULL when no specific intent was detected.
        [DetectedIntent]   NVARCHAR(100)    NULL,

        -- Confidence score returned by the bot service, range 0.0 – 1.0.
        -- NULL when the provider does not return a score.
        [ConfidenceScore]  FLOAT            NULL,

        -- Whether this bot message triggered a hand-off to a human agent.
        -- When true, a Collaboration Status transition to 'AgentHandling'
        -- follows shortly after.
        [TriggeredHandOff] BIT              NOT NULL DEFAULT 0,

        -- UTC time the bot generated this response.
        [SentAt]           DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_BotMessages] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_BotMessages_Collaborations]
            FOREIGN KEY ([CollaborationId])
            REFERENCES [Collaboration].[Collaborations] ([Id])
            ON DELETE CASCADE
    );

    CREATE INDEX [IX_BotMessages_CollaborationId]
        ON [Collaboration].[BotMessages] ([CollaborationId]);

    PRINT 'Table [Collaboration].[BotMessages] created.';
END
ELSE
    PRINT 'Table [Collaboration].[BotMessages] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 13 : [Collaboration].[Recordings]
-- Purpose  : Metadata for screen / session recordings linked to a collaboration.
--            The actual media file lives in Azure Blob Storage.
--            Multiple recordings can exist per collaboration (e.g. agent records,
--            then a supervisor also records independently).
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'Recordings'
)
BEGIN
    CREATE TABLE [Collaboration].[Recordings] (

        -- Surrogate PK.  This GUID is also used as the Blob Storage filename.
        [Id]               UNIQUEIDENTIFIER NOT NULL,

        -- The collaboration this recording captures.
        [CollaborationId]  UNIQUEIDENTIFIER NOT NULL,

        -- What was recorded.
        -- Values: 'Screen' | 'Session' | 'Audio'
        [RecordingType]    NVARCHAR(20)     NOT NULL DEFAULT 'Screen',

        -- UTC time recording started (row is inserted at this point).
        [StartedAt]        DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the recorder stopped.  NULL while still recording.
        [StoppedAt]        DATETIME2        NULL,

        -- Duration in whole seconds.  Computed when StoppedAt is set.
        [DurationSeconds]  INT              NULL,

        -- Full Blob Storage URI of the completed recording file.
        -- NULL until the upload pipeline finalises the file.
        [BlobUri]          NVARCHAR(1000)   NULL,

        -- Size of the recording file in bytes.  NULL until upload completes.
        [FileSizeBytes]    BIGINT           NULL,

        -- Processing / upload pipeline state.
        -- Values: 'Pending' | 'Processing' | 'Ready' | 'Failed'
        [Status]           NVARCHAR(20)     NOT NULL DEFAULT 'Pending',

        CONSTRAINT [PK_Recordings] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_Recordings_Collaborations]
            FOREIGN KEY ([CollaborationId])
            REFERENCES [Collaboration].[Collaborations] ([Id])
            ON DELETE CASCADE
    );

    CREATE INDEX [IX_Recordings_CollaborationId]
        ON [Collaboration].[Recordings] ([CollaborationId]);

    -- Background job query: "find all recordings still processing".
    CREATE INDEX [IX_Recordings_Status]
        ON [Collaboration].[Recordings] ([Status]);

    PRINT 'Table [Collaboration].[Recordings] created.';
END
ELSE
    PRINT 'Table [Collaboration].[Recordings] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 14 : [Collaboration].[TransferRequests]
-- Purpose  : Records every agent hand-off or transfer request.
--            Supports both directed transfers (specific target agent) and
--            queue transfers (any available agent picks it up).
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'TransferRequests'
)
BEGIN
    CREATE TABLE [Collaboration].[TransferRequests] (

        -- Surrogate PK.
        [Id]               UNIQUEIDENTIFIER NOT NULL,

        -- The collaboration being transferred.
        [CollaborationId]  UNIQUEIDENTIFIER NOT NULL,

        -- The agent initiating the transfer (the one giving up the collaboration).
        [FromUserId]       UNIQUEIDENTIFIER NOT NULL,

        -- Target agent for a directed transfer.
        -- NULL when routing to a queue rather than a specific agent.
        [ToUserId]         UNIQUEIDENTIFIER NULL,

        -- Target queue / skill-group name for pool-based routing.
        -- NULL for directed agent-to-agent transfers.
        -- Max 100 chars (queue names are short identifiers).
        [ToQueue]          NVARCHAR(100)    NULL,

        -- Optional note left by the transferring agent explaining the context
        -- for the receiving agent.
        [TransferNote]     NVARCHAR(500)    NULL,

        -- Lifecycle state of the transfer request.
        -- Values: 'Pending' | 'Accepted' | 'Declined' | 'Cancelled' | 'TimedOut'
        [Status]           NVARCHAR(20)     NOT NULL DEFAULT 'Pending',

        -- UTC time the transfer request was raised.
        [RequestedAt]      DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the target agent accepted or declined.  NULL while pending.
        [RespondedAt]      DATETIME2        NULL,

        CONSTRAINT [PK_TransferRequests] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_TransferRequests_Collaborations]
            FOREIGN KEY ([CollaborationId])
            REFERENCES [Collaboration].[Collaborations] ([Id])
            ON DELETE CASCADE,

        -- RESTRICT: preserve transfer audit trail even if agents are deactivated.
        CONSTRAINT [FK_TransferRequests_FromUser]
            FOREIGN KEY ([FromUserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE NO ACTION,

        -- SET NULL if the target agent record is ever removed.
        CONSTRAINT [FK_TransferRequests_ToUser]
            FOREIGN KEY ([ToUserId])
            REFERENCES [Collaboration].[Users] ([Id])
            ON DELETE SET NULL
    );

    CREATE INDEX [IX_TransferRequests_CollaborationId]
        ON [Collaboration].[TransferRequests] ([CollaborationId]);

    -- Dashboard: "show all pending transfers in this application".
    CREATE INDEX [IX_TransferRequests_Status]
        ON [Collaboration].[TransferRequests] ([Status]);

    PRINT 'Table [Collaboration].[TransferRequests] created.';
END
ELSE
    PRINT 'Table [Collaboration].[TransferRequests] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 15 : [Collaboration].[AuditLogs]
-- Purpose  : Immutable, append-only audit trail for all significant platform
--            events.  Rows are NEVER updated or deleted.
--            Covers: Auth, Session, Chat, Transfer, Recording, Admin, System events.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'AuditLogs'
)
BEGIN
    CREATE TABLE [Collaboration].[AuditLogs] (

        -- Surrogate PK.
        [Id]               UNIQUEIDENTIFIER NOT NULL,

        -- Related collaboration, if the event is scoped to one.  NULL for
        -- application-level or system-level events.
        [CollaborationId]  UNIQUEIDENTIFIER NULL,

        -- Related application.  NULL for platform-wide system events.
        [ApplicationId]    UNIQUEIDENTIFIER NULL,

        -- User who triggered the event.  NULL for system-generated events
        -- (e.g. background job timeouts, automated cleanup).
        [UserId]           UNIQUEIDENTIFIER NULL,

        -- High-level event category for dashboards / filtering.
        -- Values: 'Auth' | 'Session' | 'Chat' | 'Transfer' | 'Recording'
        --         | 'Admin' | 'System'
        [Category]         NVARCHAR(30)     NOT NULL,

        -- Specific event name within the category.
        -- Examples: 'UserAuthenticated', 'CollaborationStarted', 'AgentTransferred',
        --           'RecordingStarted', 'RecordingReady', 'WebhookDeliveryFailed'
        [EventName]        NVARCHAR(100)    NOT NULL,

        -- JSON payload with event-specific detail.  Schema varies by EventName.
        -- Stored as nvarchar(max).  Consider migrating to a JSON column type in
        -- SQL Server 2022+ for indexable JSON paths.
        [Payload]          NVARCHAR(MAX)    NULL,

        -- Client IPv4 or IPv6 address at the time of the event.
        -- Max 45 chars covers a full IPv6 address.
        [IpAddress]        NVARCHAR(45)     NULL,

        -- UTC time the event occurred.  Set by the server — not the client.
        [OccurredAt]       DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        CONSTRAINT [PK_AuditLogs] PRIMARY KEY ([Id])
        -- NO FK constraints intentionally: audit rows must survive even if the
        -- referenced application, collaboration, or user is later removed.
    );

    -- Primary query pattern: "show all events in date order".
    CREATE INDEX [IX_AuditLogs_OccurredAt]
        ON [Collaboration].[AuditLogs] ([OccurredAt]);

    -- Security / compliance filter: "show all events of type X".
    CREATE INDEX [IX_AuditLogs_EventName]
        ON [Collaboration].[AuditLogs] ([EventName]);

    -- Per-collaboration event timeline.
    CREATE INDEX [IX_AuditLogs_CollabId_OccurredAt]
        ON [Collaboration].[AuditLogs] ([CollaborationId], [OccurredAt]);

    -- Per-application compliance report.
    CREATE INDEX [IX_AuditLogs_AppId_OccurredAt]
        ON [Collaboration].[AuditLogs] ([ApplicationId], [OccurredAt]);

    PRINT 'Table [Collaboration].[AuditLogs] created.';
END
ELSE
    PRINT 'Table [Collaboration].[AuditLogs] already exists — skipped.';
GO


-- ================================================================================
-- TABLE 16 : [Collaboration].[WebhookNotifications]
-- Purpose  : Outbound webhook delivery log.  Each row represents one attempt to
--            POST an event payload to an application's configured webhook URL.
--            Failed deliveries are retried by a background job up to a configured
--            maximum; after that the Status is set to 'Abandoned'.
-- ================================================================================
IF NOT EXISTS (
    SELECT 1
    FROM   sys.tables  t
    JOIN   sys.schemas s ON t.schema_id = s.schema_id
    WHERE  s.name = 'Collaboration' AND t.name = 'WebhookNotifications'
)
BEGIN
    CREATE TABLE [Collaboration].[WebhookNotifications] (

        -- Surrogate PK.
        [Id]               UNIQUEIDENTIFIER NOT NULL,

        -- The application whose webhook this notification targets.
        [ApplicationId]    UNIQUEIDENTIFIER NOT NULL,

        -- Related collaboration, if the event is collaboration-scoped.
        -- NULL for application-level events (e.g. 'application.quota.exceeded').
        [CollaborationId]  UNIQUEIDENTIFIER NULL,

        -- The event type string sent in the payload.
        -- Examples: 'collaboration.started' | 'agent.transferred' |
        --           'recording.ready' | 'session.ended'
        [EventType]        NVARCHAR(100)    NOT NULL,

        -- The full JSON body that was (or will be) POSTed to the webhook endpoint.
        -- Stored as nvarchar(max) — payloads can include message history excerpts.
        [Payload]          NVARCHAR(MAX)    NOT NULL,

        -- The exact URL the payload was (or will be) posted to.
        -- Snapshot of the Application.WebhookUrl at notification creation time.
        [WebhookUrl]       NVARCHAR(500)    NOT NULL,

        -- Delivery lifecycle.
        -- Values: 'Pending' | 'Delivered' | 'Failed' | 'Retrying' | 'Abandoned'
        [Status]           NVARCHAR(20)     NOT NULL DEFAULT 'Pending',

        -- HTTP status code received from the target endpoint.
        -- NULL if no HTTP response was received (connection timeout, DNS failure).
        [HttpStatusCode]   INT              NULL,

        -- Total number of delivery attempts made so far (incremented each retry).
        [AttemptCount]     INT              NOT NULL DEFAULT 0,

        -- UTC time of the most recent delivery attempt.
        -- NULL before the first attempt is made.
        [LastAttemptAt]    DATETIME2        NULL,

        -- Error message or response body captured from the last failed attempt.
        -- Truncated to 1000 chars.
        [LastError]        NVARCHAR(1000)   NULL,

        -- UTC time the notification row was created (first attempt queued).
        [CreatedAt]        DATETIME2        NOT NULL DEFAULT GETUTCDATE(),

        -- UTC time the payload was successfully acknowledged by the target.
        -- NULL until a 2xx response is received.
        [DeliveredAt]      DATETIME2        NULL,

        CONSTRAINT [PK_WebhookNotifications] PRIMARY KEY ([Id]),

        CONSTRAINT [FK_WebhookNotifications_Applications]
            FOREIGN KEY ([ApplicationId])
            REFERENCES [Collaboration].[Applications] ([Id])
            ON DELETE CASCADE
        -- No FK on CollaborationId — a collaboration may already be ended and
        -- its row cleaned up before all retries complete.
    );

    CREATE INDEX [IX_WebhookNotifications_ApplicationId]
        ON [Collaboration].[WebhookNotifications] ([ApplicationId]);

    -- Retry worker query: "find all pending/retrying notifications".
    CREATE INDEX [IX_WebhookNotifications_Status]
        ON [Collaboration].[WebhookNotifications] ([Status]);

    -- Housekeeping: purge old delivered notifications by date.
    CREATE INDEX [IX_WebhookNotifications_CreatedAt]
        ON [Collaboration].[WebhookNotifications] ([CreatedAt]);

    PRINT 'Table [Collaboration].[WebhookNotifications] created.';
END
ELSE
    PRINT 'Table [Collaboration].[WebhookNotifications] already exists — skipped.';
GO


-- ================================================================================
-- Done
-- ================================================================================
PRINT '';
PRINT '=== Schema creation complete. ===';
PRINT 'Finished: ' + CONVERT(varchar, GETUTCDATE(), 120);
PRINT '';
PRINT 'Tables created (or already existed) in schema [Collaboration]:';
PRINT '  1.  Applications';
PRINT '  2.  ApplicationUserTypeConfigs';
PRINT '  3.  Users';
PRINT '  4.  ApplicationUsers';
PRINT '  5.  CurrentSessions';
PRINT '  6.  UserSessions';
PRINT '  7.  SessionCache';
PRINT '  8.  Collaborations';
PRINT '  9.  Participants';
PRINT '  10. Messages';
PRINT '  11. Attachments';
PRINT '  12. BotMessages';
PRINT '  13. Recordings';
PRINT '  14. TransferRequests';
PRINT '  15. AuditLogs';
PRINT '  16. WebhookNotifications';
GO
