namespace NICE.Platform.Collaboration.Core.Entities;

/// <summary>
/// Message generated by the bot (Azure AI Foundry) during a collaboration.
/// Kept separate from human messages to simplify bot analytics and re-training.
/// </summary>
public class CollaborationBotMessage
{
    public Guid Id { get; set; }

    public Guid CollaborationId { get; set; }

    /// <summary>The prompt / question that triggered this bot response.</summary>
    public string? Prompt { get; set; }

    /// <summary>The bot's generated response text.</summary>
    public string Response { get; set; } = string.Empty;

    /// <summary>
    /// Intent detected by the bot, if any (e.g. "CheckOrderStatus", "Refund").
    /// Stored for analytics.
    /// </summary>
    public string? DetectedIntent { get; set; }

    /// <summary>Confidence score returned by the bot service (0.0 – 1.0).</summary>
    public double? ConfidenceScore { get; set; }

    /// <summary>
    /// Whether the bot escalated / handed off to a human agent after this message.
    /// </summary>
    public bool TriggeredHandOff { get; set; }

    public DateTime SentAt { get; set; }

    // ── Navigation ────────────────────────────────────────────────────────
    public Collaboration CollaborationEntity { get; set; } = null!;
}
